<?php
//Last updated: 2018-09-04 20:55:50
namespace Pz\Orm;

use Pz\Router\InterfacePage;

class Page extends \Pz\Orm\Generated\Page implements InterfacePage
{
    public function getIcon() {
        return '';
    }

    /**
     * @return mixed|null|string
     */
    public function getTemplate()
    {
        return $this->objPageTempalte()->getFilename(); // TODO: Change the autogenerated stub
    }

    /**
     * @return PageTemplate|null
     */
    public function objPageTempalte()
    {
        /** @var PageTemplate $pageTemplate */
        $pageTemplate = PageTemplate::getById($this->getPdo(), $this->getTemplateFile());
        return $pageTemplate;
    }

    /**
     * @return mixed
     */
    public function objContent()
    {
        return json_decode($this->getContent());
    }
}